---

- include: disk_benchmarks.yml  # we don't use Sysbench here
- include: compile_sysbench.yml  # and now and onwards we do use Sysbench
- include: memory_benchmarks.yml
- include: network_benchmarks.yml
- include: cpu_benchmarks.yml
