---

- name: capture speedtest-cli benchmark
  shell: "sysbench --test=memory --memory-block-size=64K --memory-total-size=10G run |
  grep 'transferred (' | awk '{print $4}'"
  throttle: 1  # this is a bit arbitrary but probably sane as to not cripple whatever we're testing too much
  register: spa_memory_result
  changed_when: false

- name: get memory speed
  set_fact:
    spa_memory_speed: "{{ spa_memory_result.stdout[1:] }}"

- name: assess memory speed
  assert:
    that: (spa_memory_speed | int) > spa_memory_speed_assertion
    fail_msg: "Memory speed {{ (spa_memory_speed | int) }}MB/s
    is lesser than {{ spa_memory_speed_assertion }}MB/s"
