---

- name: wrap virtualenv installation
  block:
    - name: speedtest-cli | prepare pip
      apt:
        pkg:
          - python-pip
          - python-setuptools
          - virtualenv
        state: present
        update-cache: true
        install_recommends: false
        cache_valid_time: 3600
  rescue:
    - name: speedtest-cli | prepare pip rescued
      apt:
        pkg:
          - python3-pip
          - python3-setuptools
          - virtualenv
        state: present
        update-cache: true
        install_recommends: false
        cache_valid_time: 3600

- name: speedtest-cli | install speedtest-cli via pip
  pip:
    virtualenv: "/tmp/spa_env"
    virtualenv_python: python3
    name: speedtest-cli


- name: capture speedtest-cli benchmark
  shell: ". /tmp/spa_env/bin/activate && speedtest-cli --simple > {{ spa_speedtest_tmp_file }}"
  throttle: 1  # this is a bit arbitrary but probably sane as to not cripple whatever we're testing too much
  changed_when: false

- name: get downlink speed
  shell: "cat '{{ spa_speedtest_tmp_file }}'  | awk '{print $2}'  | sed -n '2 p'"
  register: spa_downlink_result
  changed_when: false

- name: get uplink speed
  shell: "cat '{{ spa_speedtest_tmp_file }}'  | awk '{print $2}'  | sed -n '2 p'"
  register: spa_uplink_result
  changed_when: false

- name: assess downlink speed
  assert:
    that: (spa_downlink_result.stdout | int) >= spa_downlink_assertion
    fail_msg: "WAN down link speed {{ (spa_downlink_result.stdout | int) }}Mb/s
    is lesser than {{ spa_downlink_assertion }}Mb/s"

- name: assess uplink speed
  assert:
    that: (spa_uplink_result.stdout | int) >= spa_uplink_assertion
    fail_msg: "WAN up link speed {{ (spa_uplink_result.stdout | int) }}Mb/s
        is lesser than {{ spa_uplink_assertion }}Mb/s"
