---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ansible-server-performance-assesment-test-20-04
    image: ubuntu/focal/amd64
  - name: ansible-server-performance-assesment-test-18-08
    image: ubuntu/bionic/amd64
  - name: ansible-server-performance-assesment-test-16-04
    image: ubuntu/xenial/amd64
  - name: ansible-server-performance-assesment-test-buster
    image: debian/buster/amd64
  - name: ansible-server-performance-assesment-test-stretch
    image: debian/stretch/amd64
provisioner:
  config_options:
    defaults:
      bin_ansible_callbacks: true
      display_ok_hosts: false
      display_skipped_hosts: false
      forks: 50
      internal_poll_interval: 0.001
      stdout_callback: yaml
    ssh_connection:
      pipelining: true
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: lxd
verifier:
  name: goss
  lint:
    name: yamllint
