---

- name: Verify
  hosts: all
  become: true

  # but let's see if we can make it pass/fail with some extreme values

  vars:
    ansible_become_pass: "{{ lookup('env','ANSIBLE_BECOME_PASS') }}"

  tasks:

    - name: include role
      block:
        - name: Include assertions and expect them to PASS
          include_role:
            name: ansible-server-performance-assessment
          vars:
            # those should always pass really, we've invented time machine if they don't (and it's ca. early 2000)

            spa_disk_write_run_time_assertion: 700  # value in seconds
            spa_disk_read_run_time_assertion: 700  # value in seconds

            spa_downlink_assertion: 1  # Value in Mb/s (BITS per second)
            spa_uplink_assertion: 1  # Value in Mb/s (BITS per second)

            spa_memory_speed_assertion: 100  # Value in MB/s (BYTES per second)
            spa_cpu_event_per_second_assertion: 100  # absolute number

    - name: include role
      block:
        - name: Include assertions and expect them to FAIL
          include_role:
            name: ansible-server-performance-assessment
          vars:
            # Those should never really pass unless it's 2050; but excluding my city,
            # where at that point we might be getting first broadband cable... (yay)
            spa_disk_write_run_time_assertion: 0  # value in seconds
            spa_disk_read_run_time_assertion: 0  # value in seconds

            spa_downlink_assertion: 2000  # Value in Mb/s (BITS per second)
            spa_uplink_assertion: 2000  # Value in Mb/s (BITS per second)

            spa_memory_speed_assertion: 1000000  # Value in MB/s (BYTES per second)
            spa_cpu_event_per_second_assertion: 10000  # absolute number

      rescue:
        - debug:
            msg: "All ok, we expected this to fail"
